import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "View Detail Category",
  description: "Generated by NVH",
};

export default function ViewDetailCategoryLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
