import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home Admin Page",
  description: "Generated by NVH",
};

export default function Admin() {
  return (
    <>
      <h1>Dashboard Admin</h1>
    </>
  );
}
