import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Fotgot Password Page",
  description: "Generated by NVH",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
