import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "View Detail User",
  description: "Generated by NVH",
};

export default function ViewDetailUserLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
